export type { List } from './list.interface'
export type { Guest, Permission } from './guest.interface'
export type { Board } from './board.interface'
export type { LoginAuth } from './loginAuth.interface'
export type { RegisterAuth } from './registerAuth.interface'
export type { Rol } from './rol.interface'
export type { User } from './user.interfaces'
